### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by cvalenzuela** [ml5js/ml5-website-v01#1]
Should we start using the new domain now?
The only caveat is that it needs to be a certified domain (https) to be able to access the webcam in some examples

**Comment by shiffman** [comment]
If it's hosted via github pages still it can be `https`. This is actually quite easy to do and just a matter of adding a`CNAME` file. I have ml5js.org registered, shall we use that? How does this affect #6?

**Comment by cvalenzuela** [comment]
I thought https was not supported for custom domains. I get this when chaning the domain in other projects:

![image](https://user-images.githubusercontent.com/10605821/37045782-b791cd9a-2134-11e8-93b3-0c37926eaa75.png)

But I can't enforce it. 

In any case, we just need to update the settings files in the website.

**Comment by shiffman** [comment]
Oh I think you are right, oops, somehow I had thought it worked with custom domains + https but I can't get it to work now either. We do have an ITP certificate we can probably use. @vanevery, would that only work if it's under itp.io domain? Also, this site might be helpful: https://letsencrypt.org/

**Comment by vanevery** [comment]
Let's Encrypt is great!  Happy to set you up with an itp.io domain that we have a cert for.

**Comment by cvalenzuela** [comment]
great! another quick fix is this https://js.org (maybe useful for the kinectron project too)

**Comment by cvalenzuela** [comment]
This just came out!

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by shiffman** [comment]
Oh, amazing, adding this to our June 1 milestone!

**Comment by shiffman** [comment]
Oh, oops, milestones don't go across repos. . . Well I'll make a new one for this repo.

**Comment by shiffman** [comment]
FYI the site is down as of now, I am moving it over to ml5js.org. Will post an update here when it is complete. Note the name change of the repo as well.

**Comment by shiffman** [comment]
The new website is live at ml5js.org, however, https is not yet working. Waiting for DNS to propagate to correct github pages IP address that supports https.

**Comment by shiffman** [comment]
And we're live! https://ml5js.org
