### ISSUE TITLE
"plain" image classification vs. KNN image classifier

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v01#10]
![screen shot 2018-03-07 at 7 28 19 pm](https://user-images.githubusercontent.com/191758/37126228-14f66e64-223e-11e8-8352-76637efa13ef.png)

I think the "getting started" page as well as the "Simple Image Classification" page and "Video Classification" page are erroneously referring to "KNN Image Classification." The KNN example is about training your own images with the feature vectors from the "ImageNet" model whereas the classification examples are using the actual labels from the ImageNet model. These should be called then something like:

> A simple image classification example using a pre-trained ImageNet model.

?

https://ml5js.github.io/docs/simple-image-classification-example.html
https://ml5js.github.io/docs/video-classification-example.html
https://ml5js.github.io/docs/getting-started.html

**Comment by shiffman** [comment]
Also image classification and video classification should probably both be called "simple"? (or leave "simple" out?)

**Comment by cvalenzuela** [comment]
yes! totally right, I saw it too and changed it but haven't committed it yet. Will do soon

**Comment by cvalenzuela** [comment]
Solved by #15
