### ISSUE TITLE
Tutorials? [question]

### ISSUE THREAD

**Issue by handav** [ml5js/ml5-website-v01#23]
I'm working on a tutorial for classifying multiple images, including downloading a Kaggle dataset and integrating that into the example. Do we have an idea of where to put tutorials? Should it just go alongside the example (I've made a new one called Multiple Image Classifier)?

**Comment by cvalenzuela** [comment]
There is already a link called 'Learn' and inside it, there is a subsection with 'Tutorials':
https://ml5js.github.io/docs/tutorials.html

maybe we can take Tutorials out of 'Learn' and into its own section?

**Comment by handav** [comment]
I see, no I think having it inside 'Learn' is great! I just missed it - sorry about that.
