### ISSUE TITLE
LSTM training tutorial link

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v01#33]
Workshop attendees didn't see that the tutorial link was a link on this page:

https://ml5js.github.io/docs/lstm-example.html

![screen shot 2018-05-05 at 11 53 29 am](https://user-images.githubusercontent.com/191758/39665035-2b3e9c6e-505b-11e8-96cf-5594afd67dce.png)
 
The link should go here:
https://ml5js.github.io/docs/training-lstm.html

**Comment by cvalenzuela** [comment]
fixed, see https://github.com/ml5js/ml5-website/pull/47
