### ISSUE TITLE
Pointing to sample datasets

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v01#36]
The webpage currently says:

> Sample ml5 datasets will be provided for easy use with the examples. They have been collected, cleaned, and in most cases labeled. They can be found under /docs/assets/datasets.

I don't think this is particularly helpful for users to find stuff. We should probably make a page that lists the sample datasets and/or link to the github location? 

@handav I'm just noting this here now while I'm working on the adjacent but there's no rush, we can sort this out after Eyeo!

**Comment by shiffman** [comment]
(Related to this, I think we actually have two places for datasets: 

1. https://github.com/ml5js/ml5-website/tree/source/docs/assets/data
2. https://github.com/ml5js/ml5-data-and-training/tree/master/datasets

I think I would propose putting all the data itself at `ml5-data`, but have pages that describe and link to it from the website?)

**Comment by handav** [comment]
Belated agreement with your above comment!

**Comment by shiffman** [comment]
This is good to close I think! If I'm mistaken please feel free to re-open!
