### ISSUE TITLE
fixed width font for code on homepage

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v01#39]
The code on the homepage should use a fixed width font and ideally have syntax highlighting.
![screen shot 2018-06-07 at 8 10 05 am](https://user-images.githubusercontent.com/191758/41098673-36466fc2-6a2a-11e8-9ccc-7093b19cced1.png)

**Comment by cvalenzuela** [comment]
fixed, see https://github.com/ml5js/ml5-website/pull/47
