### ISSUE TITLE
Enabeling Search

### ISSUE THREAD

**Issue by cvalenzuela** [ml5js/ml5-website-v01#4]
https://docusaurus.io/docs/en/search.html

**Comment by ashleytqy** [comment]
👋🏼hi ! can i help out with this?

**Comment by cvalenzuela** [comment]
Sure! enabling Algolia DocSearch would be great!

**Comment by ashleytqy** [comment]
@cvalenzuela do you currently have the API keys and index name? according to this [Docusaurus doc](https://github.com/facebook/Docusaurus/blob/master/docs/guides-search.md), we need to request for the site to be indexed [here](https://community.algolia.com/docsearch/), and the key and name will be sent to the owner of the site in a few days!

edit: I filled in the form and have the api key and name now :-)

**Comment by cvalenzuela** [comment]
#9 closes this. thanks @ashleytqy!
