### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by cvalenzuela** [ml5js/ml5-website-v01#46]
The site looks great on full and mobile, but half way between the two it looks like this:
![image](https://user-images.githubusercontent.com/10605821/41209410-6fe9deea-6cf9-11e8-8d6a-ef7ff7a35084.png)

want to help @matamalaortiz? I have nightmares with css

**Comment by dangdennis** [comment]
May I help? I love the idea of the library. But the page mobile-responsiveness did make me wince a little haha. Between 700px -> 1300px is where things get hairy. I can introduce a simple media query system.

**Comment by cvalenzuela** [comment]
thanks @dangdennis, but we just updated the page and now this is fixed! see https://github.com/ml5js/ml5-website/pull/47
