### ISSUE TITLE
Opening ml5.js Website on Microsoft Edge uses very High CPU and RAM

### ISSUE THREAD

**Issue by Rud156** [ml5js/ml5-website-v01#56]
I don't know if this is a problem specific to my computer but when [ml5js.org](ml5js.org) is opened using Microsoft Edge CPU, RAM usage shoots up.

It works perfectly fine in other browsers. Including Chrome, Opera and Firefox.

But I was unable to reproduce this on another Windows PC. Probably something wrong with my version of Microsoft Edge

#### Screen Shots:
![image](https://user-images.githubusercontent.com/17374395/41444828-232147de-7063-11e8-8877-ccc3eebe978c.png)

**Comment by cvalenzuela** [comment]
We are not doing much in the home page, just loading the library for the example classifier.

Can you see what happens if you open this page:
https://storage.googleapis.com/tfjs-examples/webcam-transfer-learning/dist/index.html

**Comment by Rud156** [comment]
@cvalenzuela RAM usage increases a lot. But not as much as it happens in case of [ml5js.org](ml5js.org)

Probably something wrong with my PC
