### ISSUE TITLE
Branch names

### ISSUE THREAD

**Issue by dariusk** [ml5js/ml5-website-v01#6]
What's `master` vs `source`? Is `master` where the compiled website goes, and `source` where actual docs changes are made?

**Comment by cvalenzuela** [comment]
Yep! 
From Docusaurus documentation:

> Docusaurus also supports deploying user or organization sites. These sites will be served from the master branch of the repo. So, you will want to have the Docusaurus infra, your docs, etc. in another branch (e.g., maybe call it source). To do this, just set projectName to "username.github.io" (where username is your username or organization name on GitHub) and organizationName to "username". The publish script will automatically deploy your site to the root of the master branch to be served.

**Comment by dariusk** [comment]
Cool, thanks!
