### ISSUE TITLE
Missing wordvecs10000.json for Word2Vec example

### ISSUE THREAD

**Issue by matthewkgray** [ml5js/ml5-website-v01#64]
The Word2Vec example (https://ml5js.org/docs/word2vec-example) tries to load https://ml5js.org/docs/assets/data/wordvecs/wordvecs10000.json which is not there on the website.  The relevant file appears here:
https://github.com/ml5js/ml5-examples/tree/master/p5js/Word2Vec/data

**Comment by Vigasaurus** [comment]
Currently its linking to https://github.com/ml5js/ml5-examples/tree/master/p5js/Word2Vec, is that correct, or should it actually be to the /data path?

**Comment by cvalenzuela** [comment]
Fixed in https://github.com/ml5js/ml5-website/commit/6c860e8ceda7f3c217ea487c3ac8ac9e67b5ee1f

**Comment by shiffman** [comment]
Thank you @cvalenzuela!
