### ISSUE TITLE
Add to Docusaurus users

### ISSUE THREAD

**Issue by yangshun** [ml5js/ml5-website-v01#65]
Hey there, Docusaurus maintainer here. Not really an issue. I wanted to ask if ml5 would be open to adding your logo to https://docusaurus.io/en/users? This is a really cool project! 😄

**Comment by cvalenzuela** [comment]
Sure! Docusaurus is a really cool project too! Should I submit a PR to that page?

**Comment by yangshun** [comment]
Sure thing! PRs are welcome! I would be glad to do it on your behalf if you
are unavailable.

**Comment by cvalenzuela** [comment]
That would be great. Will [this](https://ml5js.org/img/ml5.png) logo work?

**Comment by yangshun** [comment]
Yes it should work. Would be great if it was compressed first. Looking
forward to your PR!

**Comment by yangshun** [comment]
@cvalenzuela Created a PR here - https://github.com/facebook/Docusaurus/pull/786

**Comment by cvalenzuela** [comment]
amazing, thanks so much!
