### ISSUE TITLE
Style transfer instructions need clarification

### ISSUE THREAD

**Issue by RasmusFonseca** [ml5js/ml5-website-v01#69]
Thanks for an awesome resource, can't wait to get it up and running. 

I tried following the [instructions for style transfer](https://github.com/ml5js/ml5-website/blob/source/docs/examples-style-transfer-image.md) but the instructions for training a model points to a readme that only shows how to set up a tensorflow environment (and a subfolder for language models). Is the link dead or is there something I'm not getting here?

**Comment by cvalenzuela** [comment]
Hi @RasmusFonseca, we are currently working on adding more docs and training tutorials! Updates will be published soon!

**Comment by cvalenzuela** [comment]
This is now solved here: https://github.com/ml5js/training-styletransfer
