### ISSUE TITLE
Incorrect comments in code for Regression with Feature Extractor example.

### ISSUE THREAD

**Issue by mrbombmusic** [ml5js/ml5-website-v01#79]
In the function setupButtons, there is a comment which refers to the dog button which is not a part of this example. This appears to be the same comment used in Classifier example. 
![screenshot 2018-08-10 20 35 47](https://user-images.githubusercontent.com/26189509/43986362-c859214e-9cdd-11e8-90fd-c9dfdf6bb192.png)

**Comment by cvalenzuela** [comment]
updated in https://github.com/ml5js/ml5-website/commit/0e7325110ec81ed207a789c7bf8b1f622303fcf8, thanks!
