### ISSUE TITLE
font-family Apercu and Menlo

### ISSUE THREAD

**Issue by akinhwan** [ml5js/ml5-website-v01#80]
Did anyone else find the Menlo font to be a bit odd looking in conjunction with all the Apercu sans serif font on the site that is the majority?

**Comment by cvalenzuela** [comment]
In which sense is it odd looking? tagging @matamalaortiz!

**Comment by akinhwan** [comment]
It appears to only be on the front landing page, and for the two important Call To Action buttons "Get Started" and "See Examples". Or if it appears elsewhere, is hard to come by, i think it could fit in better if it were just the same font family as the other text around it. Just my opinion I was hoping others from the community might be wondering the same thing

**Comment by matamalaortiz** [comment]
I agree. It's odd that only appears once. I added some changes on a PR that includes this fix.

**Comment by cvalenzuela** [comment]
updated by @matamalaortiz in #83, closing this for now!
