### ISSUE TITLE
[Broken Example] Style transfer webcam example

### ISSUE THREAD

**Issue by 22a** [ml5js/ml5-website-v01#82]
https://ml5js.org/docs/style-transfer-webcam-example seems to be having a bit of trouble:

<img width="1392" alt="screen shot 2018-08-18 at 00 00 53" src="https://user-images.githubusercontent.com/7144173/44291954-cd113680-a279-11e8-986a-65dd3f182150.png">

A request to `https://ml5js.org/docs/assets/scripts/example-style-transfer-video.js` 404s and the page sits displaying `Loading model...`.

---

Also, just above that as part of the `You can train your own images following this tutorial.` section, the `this tutorial` is a dead link to https://github.com/ml5js/ml5-data-and-models/tree/master/training

**Comment by cvalenzuela** [comment]
Just fixed by https://github.com/ml5js/ml5-website/commit/e0024087c8c3ede9ec983e3bc1d0fae81c4d61da! thanks
